# Generated by Django 5.0.3 on 2024-03-20 08:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_interface", "0002_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="free_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
