# Generated by Django 5.0.3 on 2024-03-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_interface", "0003_person_free_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Angel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250)),
                ("is_on_heaven", models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name="AngelPage",
        ),
    ]
