# Generated by Django 5.0.3 on 2024-03-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_interface", "0004_angel_delete_angelpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Person",
        ),
    ]
