# Generated by Django 5.0.3 on 2024-03-20 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_interface", "0005_delete_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="AngelEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("event", models.JSONField()),
                ("angel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="admin_interface.angel")),
            ],
        ),
    ]
